version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: stock_price
      MYSQL_USER: stock_price_user
      MYSQL_PASSWORD: stock_price_password
      MYSQL_ROOT_PASSWORD: stock_price_password
    volumes:
      - mysql_data:/var/lib/mysql  # データ永続化のためのボリュームマウント

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000  # コマンドを更新
    volumes:
      - .:/code  # マウントポイントを更新
    ports:
      - "8000:8000"
    links:
      - db  # dbサービスへのリンクを追加

volumes:
  mysql_data:  # ボリューム名を保持